from os import path, remove
from pathlib import Path

from PyQt6 import QtCore, QtGui
from PyQt6.QtGui import QIcon
from PyQt6.QtWidgets import QWidget, QVBoxLayout, QGridLayout, QFrame, QSlider, QHBoxLayout, QLabel, QSpacerItem, \
    QSizePolicy, QSpinBox, QDoubleSpinBox, QTextEdit, QToolButton, QCheckBox, QProgressBar, QPushButton, QTableWidget, \
    QTableWidgetItem, QFileDialog, QMessageBox

from CONFIG import DATABASE_NAME
from classes.ScanDB import ScanDB
from classes.branch_classes.CsvMeshDataExporter import CsvMeshDataExporter
from classes.branch_classes.MeshMSEConst import MeshMSEConstDB
from classes.branch_classes.MeshStatisticCalculator import MeshStatisticCalculator
from utils.mesh_utils.mesh_exporters.DxfMeshExporter import DxfMeshExporter
from utils.mesh_utils.mesh_exporters.PlyMeshExporter import PlyMeshExporter
from utils.mesh_utils.mesh_exporters.PlyMseMeshExporter import PlyMseMeshExporter
from utils.start_db import engine, create_db


class ASTinUI(QWidget):

    def __init__(self):
        super().__init__()
        self.setupUi()
        self.base_filepath = None
        self.max_border_length_m = self.slider_max_border_lenght.value()
        self.target_mse = self.slider_target_mse.value()
        self.max_iteration_count = self.slider_iteration_counter.value()
        self.file_path_button.clicked.connect(self.open_file_dialog_base_filepath)
        self.file_path_text.textChanged.connect(self.base_filepath_from_text_line)
        self.slider_max_border_lenght.valueChanged.connect(self.sliders_update)
        self.slider_target_mse.valueChanged.connect(self.sliders_update)
        self.slider_iteration_counter.valueChanged.connect(self.sliders_update)
        self.sb_max_border_lenght.valueChanged.connect(self.sb_update)
        self.sb_target_mse.valueChanged.connect(self.sb_update)
        self.sb_iteration_counter.valueChanged.connect(self.sb_update)
        self.progressBar.setProperty("value", 0)
        self.start_button.clicked.connect(self.start_calculation)

    def start_calculation(self):
        self.start_button.setEnabled(False)
        dir_path = path.dirname(self.base_filepath)
        create_db()
        scan_name = path.basename(self.base_filepath).split(".")[0]
        scan = ScanDB(scan_name=scan_name)
        scan.load_scan_from_file(file_name=self.base_filepath)
        self.progressBar.setProperty("value", 10)
        ########################################################################
        self.target_mse = self.target_mse / 100
        mesh = MeshMSEConstDB(scan, max_border_length_m=self.max_border_length_m,
                              max_triangle_mse_m=self.target_mse,
                              n=self.max_iteration_count, calk_with_brute_force=False)
        progress = self.progressBar.value()
        progress_step = self.calc_progress_bar_step()
        for iteration in mesh.calculate_mesh():
            progress += progress_step
            self.progressBar.setProperty("value", progress)
        self.progressBar.setProperty("value", 80)
        ########################################################################
        if self.cb_save_full_tin_csv_log.isChecked():
            CsvMeshDataExporter(mesh.mesh).export_mesh_data(file_path=dir_path)
        stat_calculator = MeshStatisticCalculator(mesh.mesh, file_path=dir_path)
        if self.cb_save_base_stat.isChecked():
            MeshStatisticCalculator(mesh.mesh).save_statistic(file_path=dir_path)
        self.progressBar.setProperty("value", 85)
        ########################################################################
        if self.cb_save_scan_to_txt.isChecked():
            mesh.sampled_scan.save_scan_in_file(file_path=dir_path)
        if self.cb_save_dxf.isChecked():
            DxfMeshExporter(mesh=mesh).export(file_path=dir_path)
        if self.cb_ply_rgb.isChecked():
            PlyMeshExporter(mesh=mesh).export(file_path=dir_path)
        if self.cb_ply_mse.isChecked():
            PlyMseMeshExporter(mesh=mesh, min_mse=0, max_mse=self.target_mse).export(file_path=dir_path)
        self.progressBar.setProperty("value", 90)
        ########################################################################
        graf_dict = {"rmse": self.cb_mse_graf.isChecked(),
                     "r": self.cb_r_graf.isChecked(),
                     "area": self.cb_area_graf.isChecked(),
                     "pair_plot": self.cb_pair_plot_graf.isChecked()}
        stat_calculator.save_distributions_histograms(graf_dict, file_path=dir_path)
        self.progressBar.setProperty("value", 100)
        ########################################################################
        stat_dict = stat_calculator.get_statistic()
        self.result_table.setEnabled(True)
        self.result_table.setItem(0, 0, QTableWidgetItem(str(len(scan))))
        self.result_table.setItem(0, 1, QTableWidgetItem(str(len(mesh.sampled_scan))))
        self.result_table.setItem(0, 2, QTableWidgetItem(str(len(mesh.mesh))))
        self.result_table.setItem(0, 3, QTableWidgetItem(str(round(mesh.mesh.mse, 4))))
        self.result_table.setItem(0, 4, QTableWidgetItem(str(round(stat_dict["Max_MSE"], 4))))
        self.result_table.setItem(0, 5, QTableWidgetItem(str(mesh.count_of_bad_tr)))
        self.result_table.setItem(0, 6, QTableWidgetItem(str(mesh.loop_counter)))
        ########################################################################
        if self.cb_save_db.isChecked() is False:
            engine.dispose()
            remove(path.join(".", DATABASE_NAME))
        ########################################################################
        self.start_button.setEnabled(True)
        dig = QMessageBox(self)
        dig.setWindowTitle("Result")
        dig.setText("Расчет завершен!")
        dig.setIcon(QMessageBox.Icon.Information)
        dig.exec()

    def sb_update(self):
        self.max_border_length_m = self.sb_max_border_lenght.value()
        self.target_mse = self.sb_target_mse.value()
        self.max_iteration_count = self.sb_iteration_counter.value()
        self.slider_max_border_lenght.setValue(int(self.max_border_length_m))
        self.slider_target_mse.setValue(int(self.target_mse))
        self.slider_iteration_counter.setValue(int(self.max_iteration_count))

    def sliders_update(self):
        self.max_border_length_m = self.slider_max_border_lenght.value()
        self.target_mse = self.slider_target_mse.value()
        self.max_iteration_count = self.slider_iteration_counter.value()
        self.sb_max_border_lenght.setValue(self.max_border_length_m)
        self.sb_target_mse.setValue(self.target_mse)
        self.sb_iteration_counter.setValue(self.max_iteration_count)

    def open_file_dialog_base_filepath(self):
        filename, ok = QFileDialog.getOpenFileName(
            self,
            "Select a File",
            ".",
            "PointCloud (*.txt *.ascii)"
        )
        if filename:
            path = Path(filename)
            self.file_path_text.setText(str(filename))
            self.base_filepath = str(path)

    def base_filepath_from_text_line(self):
        self.base_filepath = self.file_path_text.toPlainText()
        if self.base_filepath:
            self.start_button.setEnabled(True)
        else:
            self.start_button.setEnabled(False)

    def calc_progress_bar_step(self):
        return int(70 / (self.max_iteration_count + 1))

    def setupUi(self):
        self.setObjectName("Form")
        self.setWindowIcon(QIcon("icon.ico"))
        self.setEnabled(True)
        self.resize(1010, 615)
        self.setMinimumSize(QtCore.QSize(1010, 615))
        self.setMaximumSize(QtCore.QSize(1010, 590))
        self.verticalLayoutWidget = QWidget(parent=self)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 996, 668))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_4 = QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.line_2 = QFrame(parent=self.verticalLayoutWidget)
        self.line_2.setFrameShadow(QFrame.Shadow.Plain)
        self.line_2.setLineWidth(28)
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 2, 1, 1, 1)
        self.gridLayout_2 = QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.slider_target_mse = QSlider(parent=self.verticalLayoutWidget)
        self.slider_target_mse.setMinimum(0)
        self.slider_target_mse.setMaximum(100)
        self.slider_target_mse.setProperty("value", 50)
        self.slider_target_mse.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_target_mse.setObjectName("slider_target_mse")
        self.gridLayout_2.addWidget(self.slider_target_mse, 1, 1, 1, 1)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QLabel(parent=self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_5 = QLabel(parent=self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 4, 1, 1, 1)
        self.label_iteration_counter = QLabel(parent=self.verticalLayoutWidget)
        self.label_iteration_counter.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_iteration_counter.setObjectName("label_iteration_counter")
        self.gridLayout_4.addWidget(self.label_iteration_counter, 5, 0, 1, 1)
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QSpacerItem(20, 10, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.sb_iteration_counter = QSpinBox(parent=self.verticalLayoutWidget)
        self.sb_iteration_counter.setMinimum(0)
        self.sb_iteration_counter.setMaximum(50)
        self.sb_iteration_counter.setProperty("value", 10)
        self.sb_iteration_counter.setObjectName("sb_iteration_counter")
        self.verticalLayout_2.addWidget(self.sb_iteration_counter)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 5, 2, 1, 1)
        self.label_target_mse = QLabel(parent=self.verticalLayoutWidget)
        self.label_target_mse.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_target_mse.setObjectName("label_target_mse")
        self.gridLayout_4.addWidget(self.label_target_mse, 4, 0, 1, 1)
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QLabel(parent=self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem2 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label_2 = QLabel(parent=self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.slider_iteration_counter = QSlider(parent=self.verticalLayoutWidget)
        self.slider_iteration_counter.setMinimum(0)
        self.slider_iteration_counter.setMaximum(50)
        self.slider_iteration_counter.setProperty("value", 10)
        self.slider_iteration_counter.setSliderPosition(10)
        self.slider_iteration_counter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_iteration_counter.setObjectName("slider_iteration_counter")
        self.gridLayout.addWidget(self.slider_iteration_counter, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 5, 1, 1, 1)
        self.gridLayout_5 = QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.slider_max_border_lenght = QSlider(parent=self.verticalLayoutWidget)
        self.slider_max_border_lenght.setMinimum(1)
        self.slider_max_border_lenght.setMaximum(100)
        self.slider_max_border_lenght.setProperty("value", 20)
        self.slider_max_border_lenght.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_max_border_lenght.setObjectName("slider_max_border_lenght")
        self.gridLayout_5.addWidget(self.slider_max_border_lenght, 1, 1, 1, 1)
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QLabel(parent=self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        spacerItem3 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.label_9 = QLabel(parent=self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 3, 1, 1, 1)
        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem4 = QSpacerItem(20, 10, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.sb_target_mse = QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.sb_target_mse.setEnabled(True)
        self.sb_target_mse.setMaximumSize(QtCore.QSize(48, 16777215))
        self.sb_target_mse.setDecimals(1)
        self.sb_target_mse.setMaximum(100.0)
        self.sb_target_mse.setSingleStep(0.1)
        self.sb_target_mse.setProperty("value", 50.0)
        self.sb_target_mse.setObjectName("sb_target_mse")
        self.verticalLayout_3.addWidget(self.sb_target_mse)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 4, 2, 1, 1)
        self.label_vax_border_length = QLabel(parent=self.verticalLayoutWidget)
        self.label_vax_border_length.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_vax_border_length.setObjectName("label_vax_border_length")
        self.gridLayout_4.addWidget(self.label_vax_border_length, 3, 0, 1, 1)
        self.verticalLayout_4 = QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem5 = QSpacerItem(20, 10, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.sb_max_border_lenght = QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.sb_max_border_lenght.setEnabled(True)
        self.sb_max_border_lenght.setMaximumSize(QtCore.QSize(48, 16777215))
        self.sb_max_border_lenght.setSingleStep(0.1)
        self.sb_max_border_lenght.setProperty("value", 20.0)
        self.sb_max_border_lenght.setObjectName("sb_max_border_lenght")
        self.verticalLayout_4.addWidget(self.sb_max_border_lenght)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 3, 2, 1, 1)
        self.verticalLayout_5 = QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem6 = QSpacerItem(0, 0, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.file_path_text = QTextEdit(parent=self.verticalLayoutWidget)
        self.file_path_text.setMinimumSize(QtCore.QSize(0, 20))
        self.file_path_text.setMaximumSize(QtCore.QSize(16777215, 25))
        self.file_path_text.setObjectName("file_path_text")
        self.verticalLayout_5.addWidget(self.file_path_text)
        spacerItem7 = QSpacerItem(20, 10, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 1, 1, 1, 1)
        self.Label_scan_name = QLabel(parent=self.verticalLayoutWidget)
        self.Label_scan_name.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Label_scan_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Label_scan_name.setObjectName("Label_scan_name")
        self.gridLayout_4.addWidget(self.Label_scan_name, 1, 0, 1, 1)
        self.line_3 = QFrame(parent=self.verticalLayoutWidget)
        self.line_3.setFrameShadow(QFrame.Shadow.Plain)
        self.line_3.setLineWidth(28)
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 2, 2, 1, 1)
        self.line = QFrame(parent=self.verticalLayoutWidget)
        self.line.setFrameShadow(QFrame.Shadow.Plain)
        self.line.setLineWidth(28)
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 2, 0, 1, 1)
        self.verticalLayout_8 = QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem8 = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.verticalLayout_8.addItem(spacerItem8)
        self.file_path_button = QToolButton(parent=self.verticalLayoutWidget)
        self.file_path_button.setObjectName("file_path_button")
        self.verticalLayout_8.addWidget(self.file_path_button)
        spacerItem9 = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.verticalLayout_8.addItem(spacerItem9)
        self.gridLayout_4.addLayout(self.verticalLayout_8, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.gridLayout_6 = QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.line_7 = QFrame(parent=self.verticalLayoutWidget)
        self.line_7.setFrameShadow(QFrame.Shadow.Plain)
        self.line_7.setLineWidth(28)
        self.line_7.setFrameShape(QFrame.Shape.HLine)
        self.line_7.setObjectName("line_7")
        self.gridLayout_6.addWidget(self.line_7, 0, 1, 1, 1)
        self.label_16 = QLabel(parent=self.verticalLayoutWidget)
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 1, 0, 1, 1)
        self.gridLayout_3 = QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cb_ply_rgb = QCheckBox(parent=self.verticalLayoutWidget)
        self.cb_ply_rgb.setEnabled(True)
        self.cb_ply_rgb.setObjectName("cb_ply_rgb")
        self.horizontalLayout_5.addWidget(self.cb_ply_rgb)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 3, 3, 1, 1)
        self.cb_r_graf = QCheckBox(parent=self.verticalLayoutWidget)
        self.cb_r_graf.setEnabled(True)
        self.cb_r_graf.setObjectName("cb_r_graf")
        self.gridLayout_3.addWidget(self.cb_r_graf, 3, 2, 1, 1)
        self.line_5 = QFrame(parent=self.verticalLayoutWidget)
        self.line_5.setFrameShadow(QFrame.Shadow.Plain)
        self.line_5.setLineWidth(28)
        self.line_5.setFrameShape(QFrame.Shape.HLine)
        self.line_5.setObjectName("line_5")
        self.gridLayout_3.addWidget(self.line_5, 1, 3, 1, 1)
        self.gridLayout_8 = QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem10 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.gridLayout_8.addItem(spacerItem10, 0, 0, 1, 1)
        self.label_13 = QLabel(parent=self.verticalLayoutWidget)
        self.label_13.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 0, 1, 1, 1)
        spacerItem11 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.gridLayout_8.addItem(spacerItem11, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_8, 0, 2, 1, 1)
        self.gridLayout_7 = QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem12 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.gridLayout_7.addItem(spacerItem12, 0, 2, 1, 1)
        self.label_11 = QLabel(parent=self.verticalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 0, 1, 1, 1)
        spacerItem13 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.gridLayout_7.addItem(spacerItem13, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.cb_mse_graf = QCheckBox(parent=self.verticalLayoutWidget)
        self.cb_mse_graf.setEnabled(True)
        self.cb_mse_graf.setObjectName("cb_mse_graf")
        self.gridLayout_3.addWidget(self.cb_mse_graf, 2, 2, 1, 1)
        self.cb_area_graf = QCheckBox(parent=self.verticalLayoutWidget)
        self.cb_area_graf.setEnabled(True)
        self.cb_area_graf.setObjectName("cb_area_graf")
        self.gridLayout_3.addWidget(self.cb_area_graf, 4, 2, 1, 1)
        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout_9 = QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem14 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.gridLayout_9.addItem(spacerItem14, 0, 0, 1, 1)
        spacerItem15 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.gridLayout_9.addItem(spacerItem15, 0, 2, 1, 1)
        self.label_14 = QLabel(parent=self.verticalLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_9.addWidget(self.label_14, 0, 1, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_9)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 0, 3, 1, 1)
        self.line_6 = QFrame(parent=self.verticalLayoutWidget)
        self.line_6.setFrameShadow(QFrame.Shadow.Plain)
        self.line_6.setLineWidth(28)
        self.line_6.setFrameShape(QFrame.Shape.HLine)
        self.line_6.setObjectName("line_6")
        self.gridLayout_3.addWidget(self.line_6, 1, 2, 1, 1)
        self.line_4 = QFrame(parent=self.verticalLayoutWidget)
        self.line_4.setFrameShadow(QFrame.Shadow.Plain)
        self.line_4.setLineWidth(28)
        self.line_4.setFrameShape(QFrame.Shape.HLine)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 1, 0, 1, 1)
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cb_save_dxf = QCheckBox(parent=self.verticalLayoutWidget)
        self.cb_save_dxf.setEnabled(True)
        self.cb_save_dxf.setChecked(True)
        self.cb_save_dxf.setObjectName("cb_save_dxf")
        self.horizontalLayout_3.addWidget(self.cb_save_dxf)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 2, 3, 1, 1)
        self.cb_pair_plot_graf = QCheckBox(parent=self.verticalLayoutWidget)
        self.cb_pair_plot_graf.setEnabled(True)
        self.cb_pair_plot_graf.setObjectName("cb_pair_plot_graf")
        self.gridLayout_3.addWidget(self.cb_pair_plot_graf, 5, 2, 1, 1)
        self.cb_save_db = QCheckBox(parent=self.verticalLayoutWidget)
        self.cb_save_db.setEnabled(True)
        self.cb_save_db.setChecked(False)
        self.cb_save_db.setObjectName("cb_save_res_scan_to_txt")
        self.gridLayout_3.addWidget(self.cb_save_db, 5, 0, 1, 1)
        self.cb_save_full_tin_csv_log = QCheckBox(parent=self.verticalLayoutWidget)
        self.cb_save_full_tin_csv_log.setEnabled(True)
        self.cb_save_full_tin_csv_log.setObjectName("cb_save_full_tin_csv_log")
        self.gridLayout_3.addWidget(self.cb_save_full_tin_csv_log, 4, 0, 1, 1)
        self.cb_save_scan_to_txt = QCheckBox(parent=self.verticalLayoutWidget)
        self.cb_save_scan_to_txt.setEnabled(True)
        self.cb_save_scan_to_txt.setChecked(True)
        self.cb_save_scan_to_txt.setObjectName("cb_save_db")
        self.gridLayout_3.addWidget(self.cb_save_scan_to_txt, 2, 0, 1, 1)
        self.cb_save_base_stat = QCheckBox(parent=self.verticalLayoutWidget)
        self.cb_save_base_stat.setEnabled(True)
        self.cb_save_base_stat.setObjectName("cb_save_base_stat")
        self.gridLayout_3.addWidget(self.cb_save_base_stat, 3, 0, 1, 1)
        self.cb_ply_mse = QCheckBox(parent=self.verticalLayoutWidget)
        self.cb_ply_mse.setEnabled(True)
        self.cb_ply_mse.setObjectName("cb_ply_mse")
        self.gridLayout_3.addWidget(self.cb_ply_mse, 4, 3, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 1, 1, 1, 1)
        self.line_8 = QFrame(parent=self.verticalLayoutWidget)
        self.line_8.setFrameShadow(QFrame.Shadow.Plain)
        self.line_8.setLineWidth(28)
        self.line_8.setFrameShape(QFrame.Shape.HLine)
        self.line_8.setObjectName("line_8")
        self.gridLayout_6.addWidget(self.line_8, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.progressBar = QProgressBar(parent=self.verticalLayoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_7.addWidget(self.progressBar)
        self.start_button = QPushButton(parent=self.verticalLayoutWidget)
        self.start_button.setEnabled(False)
        self.start_button.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.start_button.setFlat(False)
        self.start_button.setObjectName("start_button")
        self.horizontalLayout_7.addWidget(self.start_button)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.result_table = QTableWidget(parent=self.verticalLayoutWidget)
        self.result_table.setEnabled(False)
        self.result_table.setMinimumSize(QtCore.QSize(994, 109))
        self.result_table.setMaximumSize(QtCore.QSize(994, 109))
        self.result_table.setObjectName("result_table")
        self.result_table.setColumnCount(7)
        self.result_table.setRowCount(1)
        self.result_table.setColumnWidth(0, 130)
        self.result_table.setColumnWidth(1, 130)
        self.result_table.setColumnWidth(2, 120)
        self.result_table.setColumnWidth(3, 100)
        self.result_table.setColumnWidth(4, 60)
        self.result_table.setColumnWidth(5, 180)
        self.result_table.setColumnWidth(6, 90)
        item = QTableWidgetItem()
        self.result_table.setVerticalHeaderItem(0, item)
        item = QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.result_table.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.result_table.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.result_table.setHorizontalHeaderItem(2, item)
        item = QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.result_table.setHorizontalHeaderItem(3, item)
        item = QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.result_table.setHorizontalHeaderItem(4, item)
        item = QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.result_table.setHorizontalHeaderItem(5, item)
        item = QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.result_table.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.result_table)
        self.retranslateUi()
        self.slider_iteration_counter.sliderMoved['int'].connect(self.sb_iteration_counter.setValue)
        self.sb_iteration_counter.valueChanged['int'].connect(self.slider_iteration_counter.setValue)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "AccurateSparseTIN"))
        self.label_4.setText(_translate("Form", "Точнее"))
        self.label_5.setText(_translate("Form", "Грубее"))
        self.label_iteration_counter.setText(_translate("Form", "Количество\nитераций:"))
        self.label_target_mse.setText(_translate("Form", "Целевая\nСКП\nповерхности, см:"))
        self.label.setText(_translate("Form", "Быстро"))
        self.label_2.setText(_translate("Form", "Долго"))
        self.label_8.setText(_translate("Form", "Меньше"))
        self.label_9.setText(_translate("Form", "Больше"))
        self.label_vax_border_length.setText(_translate("Form", "Максимальная\n"
                                                                "сторона\nполигона, м:"))
        self.Label_scan_name.setText(_translate("Form", "Исходный\nскан:"))
        self.file_path_button.setText(_translate("Form", "..."))
        self.label_16.setText(_translate("Form", "Настройки\nвыводимой\nинформации:"))
        self.cb_ply_rgb.setText(_translate("Form", "Сохранить TIN поверхность в PLY формате\n"
                                                   "(цвет RGB  исходного облака)"))
        self.cb_r_graf.setText(_translate("Form", "Распределение количества\nизбыточных данных"))
        self.label_13.setText(_translate("Form", "Графики распределения\n"
                                                 "параметров TIN поверхности"))
        self.label_11.setText(_translate("Form", "Сохраняемая информация"))
        self.cb_mse_graf.setText(_translate("Form", "Распределение СКП\n"
                                                    "в треугольниках поверхности"))
        self.cb_area_graf.setText(_translate("Form", "Распределение площади\n"
                                                     "треугольников в поверхности"))
        self.label_14.setText(_translate("Form", "Создать TIN поверхность"))
        self.cb_save_dxf.setText(_translate("Form", "Сохранить TIN поверхность в DXF формате"))
        self.cb_pair_plot_graf.setText(_translate("Form", "Совмещенный график\nраспределения"))
        self.cb_save_db.setText(_translate("Form", "Сохранить служебную базу данных"))
        self.cb_save_full_tin_csv_log.setText(_translate("Form", "Сохранить полное описание "
                                                                 "результрующей\nповерхности в CSV файле"))
        self.cb_save_scan_to_txt.setText(_translate("Form", "Сохранить результирующий скан "
                                                                              "в TXT формате"))
        self.cb_save_base_stat.setText(_translate("Form", "Сохранить общую статистику\n"
                                                          "поверхности в CSV файле"))
        self.cb_ply_mse.setText(_translate("Form", "Сохранить TIN поверхность в PLY формате\n"
                                                   "(цвет пропорционален СКП)"))
        self.start_button.setText(_translate("Form", "Запуск разрежения"))
        item = self.result_table.verticalHeaderItem(0)
        item.setText(_translate("Form", "Рассчитанные значения"))
        item = self.result_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "К-во точек в исх.облаке"))
        item = self.result_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "К-во в точек раз.облаке"))
        item = self.result_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "К-во полигонов в TIN"))
        item = self.result_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "СКП поверхности"))
        item = self.result_table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Макс.СКП"))
        item = self.result_table.horizontalHeaderItem(5)
        item.setText(_translate("Form", "К-во п-ов, превышающих уст.СКП"))
        item = self.result_table.horizontalHeaderItem(6)
        item.setText(_translate("Form", "К-во итераций"))
